// <auto-generated />
using System;
using Interasian.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Interasian.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250611115037_AddedCreator")]
    partial class AddedCreator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Interasian.API.Models.Listing", b =>
                {
                    b.Property<int>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingId"));

                    b.Property<int?>("BathRooms")
                        .HasColumnType("int");

                    b.Property<int?>("BedRooms")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FloorArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListingId");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            ListingId = 1,
                            BathRooms = 3,
                            BedRooms = 4,
                            Creator = "",
                            Description = "A luxurious villa with ocean view and private pool.",
                            FloorArea = "350 sqm",
                            LandArea = "500 sqm",
                            Location = "Boracay Island",
                            Owner = "John Smith",
                            Price = 15000000m,
                            PropertyType = "House with Lot",
                            Status = true,
                            Title = "Beachside Villa"
                        },
                        new
                        {
                            ListingId = 2,
                            BathRooms = 1,
                            BedRooms = 2,
                            Creator = "",
                            Description = "Modern condo in the heart of the business district.",
                            FloorArea = "60 sqm",
                            LandArea = "60 sqm",
                            Location = "Makati City",
                            Owner = "Jane Doe",
                            Price = 4500000m,
                            PropertyType = "Condo",
                            Status = true,
                            Title = "Urban Condo"
                        },
                        new
                        {
                            ListingId = 3,
                            BathRooms = 8,
                            BedRooms = 8,
                            Creator = "",
                            Description = "Prime commercial building with 5 floors suitable for office spaces.",
                            FloorArea = "3500 sqm",
                            LandArea = "1200 sqm",
                            Location = "Ortigas Center",
                            Owner = "Metro Properties Inc.",
                            Price = 75000000m,
                            PropertyType = "Commercial Building",
                            Status = true,
                            Title = "Ayala Building"
                        },
                        new
                        {
                            ListingId = 4,
                            BathRooms = 5,
                            BedRooms = 5,
                            Creator = "jtangpuz@guardian.ph",
                            Description = "Beautiful vacant lot with panoramic view of Taal Lake.",
                            LandArea = "800 sqm",
                            Location = "Lapu-Lapu City",
                            Owner = "Connie Tangpuz",
                            Price = 6500000m,
                            PropertyType = "House with Lot",
                            Status = true,
                            Title = "Tangpuz House"
                        },
                        new
                        {
                            ListingId = 5,
                            BathRooms = 4,
                            BedRooms = 5,
                            Creator = "jtangpuz@guardian.ph",
                            Description = "Spacious family home in a gated community with garden and garage.",
                            FloorArea = "280 sqm",
                            LandArea = "350 sqm",
                            Location = "Alabang, Muntinlupa",
                            Owner = "Maria Santos",
                            Price = 18500000m,
                            PropertyType = "House with Lot",
                            Status = true,
                            Title = "Suburban Family Home"
                        });
                });

            modelBuilder.Entity("Interasian.API.Models.ListingImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ImageId");

                    b.HasIndex("ListingId");

                    b.ToTable("ListingImages");
                });

            modelBuilder.Entity("Interasian.API.Models.ListingImage", b =>
                {
                    b.HasOne("Interasian.API.Models.Listing", "Listing")
                        .WithMany("Images")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Interasian.API.Models.Listing", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
